# Generated by Django 2.2.5 on 2019-10-11 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creating')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of updating')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Object is deleted.')),
                ('title', models.CharField(max_length=150, verbose_name='Article header')),
                ('description', models.TextField(max_length=1000, verbose_name='Article description')),
                ('text', models.TextField(verbose_name='Article text')),
                ('preview_image', models.URLField(verbose_name='Preview image of the article')),
                ('slug', models.SlugField(allow_unicode=True, max_length=150, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creating')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of updating')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Object is deleted.')),
                ('text', models.TextField(max_length=512, verbose_name='Comment text')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Object is deleted.')),
                ('url', models.URLField(verbose_name='Image URL')),
                ('type', models.CharField(choices=[('IMG', 'Image'), ('VID', 'Video'), ('URL', 'URL')], max_length=3, verbose_name='Resources')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='articles.Article')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='articles.Comment')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
